// src/tools/project-initializer.ts
import * as path from 'path';
import * as fs from 'fs';

/**
 * 初始化项目结构 (创建必要的环境文件)
 * @param projectRoot 项目在 codes 下的根目录
 * @param language 目标语言
 */
export async function initialProject(projectRoot: string, language: string) {
    
    // 1. 确保项目根目录存在
    if (!fs.existsSync(projectRoot)) {
        fs.mkdirSync(projectRoot, { recursive: true });
    }
    
    // 2. 通用：创建 README
    const readmePath = path.join(projectRoot, 'README.md');
    if (!fs.existsSync(readmePath)) {
        fs.writeFileSync(readmePath, `# Project ${path.basename(projectRoot)}\n\nGenerated by aicase (${language})`, 'utf8');
    }

    // 3. 语言特定初始化
    switch (language) {
        case 'python':
            initPython(projectRoot);
            break;

    }
}

function initPython(root: string) {
    const envFile = path.join(root, '.env');
    if (!fs.existsSync(envFile)) {
        fs.writeFileSync(envFile, 'PYTHONPATH=.', 'utf8');
    }
}

export async function removeProject(projectRoot: string) {
    if (fs.existsSync(projectRoot)) {
        try {
            fs.rmSync(projectRoot, { recursive: true, force: true });
            console.log(`[ProjectInitializer] 项目目录已删除: ${projectRoot}`);
        } catch (error) {
            console.error(`[ProjectInitializer] 删除项目目录失败: ${error}`);
            throw error;
        }
    }
}